# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZynqCons.xdc

# Block Designs: bd/ZynqBlockDesign/ZynqBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign || ORIG_REF_NAME==ZynqBlockDesign} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_processing_system7_0_0/ZynqBlockDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_processing_system7_0_0 || ORIG_REF_NAME==ZynqBlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_proc_sys_reset_0_0/ZynqBlockDesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_proc_sys_reset_0_0 || ORIG_REF_NAME==ZynqBlockDesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_axi_uartlite_0_0/ZynqBlockDesign_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_axi_uartlite_0_0 || ORIG_REF_NAME==ZynqBlockDesign_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_axi_gpio_0_0/ZynqBlockDesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_axi_gpio_0_0 || ORIG_REF_NAME==ZynqBlockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_xbar_0/ZynqBlockDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_xbar_0 || ORIG_REF_NAME==ZynqBlockDesign_xbar_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_auto_pc_0/ZynqBlockDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_auto_pc_0 || ORIG_REF_NAME==ZynqBlockDesign_auto_pc_0} -quiet] -quiet

# IP: bd/ZynqBlockDesign/ip/ZynqBlockDesign_axi_interconnect_0_0/ZynqBlockDesign_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqBlockDesign_axi_interconnect_0_0 || ORIG_REF_NAME==ZynqBlockDesign_axi_interconnect_0_0} -quiet] -quiet

# XDC: c:/Users/quang/Desktop/Pynq/TRNG-Pynq/TRNG-Pynq.gen/sources_1/bd/ZynqBlockDesign/ZynqBlockDesign_ooc.xdc
