set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048_in_context.xdc id:1 order:EARLY scoped_inst:smbus/fifo} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048_in_context.xdc id:2 order:EARLY scoped_inst:fifo_8} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc id:3 order:EARLY scoped_inst:audio/playback_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc id:4 order:EARLY scoped_inst:audio/record_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc id:5 order:EARLY scoped_inst:fifo_32_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc rfile:../../../../../../../vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512_in_context.xdc id:6 order:EARLY scoped_inst:fifo_32_1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc rfile:../../../../../../../vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc id:7 order:EARLY scoped_inst:xillybus_ins/system_i/vivado_system_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc rfile:../../../../../../../vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc id:8 order:EARLY scoped_inst:xillybus_ins/system_i/vivado_system_i/rst_processing_system7_0_100M/U0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/xillydemo.xdc rfile:../../../../../../../vivado-essentials/xillydemo.xdc id:9} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:10} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins smbus/fifo/clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells smbus/fifo]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fifo_8/clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fifo_8]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins audio/playback_fifo/clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells audio/playback_fifo]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins audio/record_fifo/clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells audio/record_fifo]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fifo_32_0/clk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fifo_32_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fifo_32_1/clk]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fifo_32_1]
current_instance xillybus_ins/system_i/vivado_system_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:7 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_fpga_1 [get_pins {PS7_i/FCLKCLK[1]}]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list xillybus_ins/system_i/vivado_system_i/rst_processing_system7_0_100M/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D xillybus_ins/system_i/vivado_system_i/rst_processing_system7_0_100M/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name gclk [get_ports clk_100]
set_property src_info {type:XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_100]
set_property src_info {type:XDC file:9 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay 5.500 [get_ports vga*]
set_property src_info {type:XDC file:10 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0/inst]
set_property src_info {type:XDC file:10 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/rst_processing_system7_0_100M/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smbus/fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells fifo_8]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells fifo_32_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells fifo_32_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells audio/playback_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells audio/record_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/xillybus_lite_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/xillybus_ip_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/xillyvga_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph/s00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph/m00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph/m01_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph/m02_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/processing_system7_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/rst_processing_system7_0_100M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xillybus_ins/system_i/vivado_system_i/xlconcat_0]
