set_property SRC_FILE_INFO {cfile:C:/Users/quang/Downloads/NBM/FINALNBM/FINALNBM.srcs/constrs_1/new/btl.xdc rfile:../../../FINALNBM.srcs/constrs_1/new/btl.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports reset_rtl]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports uart_rtl_txd]
