# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/3007/hdl
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ec67/hdl
  } {
      D:/Study/Tai_lieu/Nhung_bao_mat/xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Study/Tai_lieu/Nhung_bao_mat/xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/3007/hdl
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ec67/hdl
  } {
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/realtime/vga_fifo_stub.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/realtime/fifo_8x2048_stub.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/realtime/fifo_32x512_stub.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/xillydemo.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/xillybus_core.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/xillybus.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/system.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/smbus.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/i2s_audio.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_zero_digits_data_V_RAM_AUTO_1R1W.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_udiv_128ns_64ns_64_132_seq_1.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_q_digits_data_V_RAM_AUTO_0R0W.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_operator_Pipeline_OUTER_INNER.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_operator_mul.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_operator_lt.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_operator_1_Pipeline_OUTER_INNER.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_operator_1.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_mul_64ns_65ns_192_3_1.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_mul_64ns_64ns_128_3_1.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_modulus_digits_data_V_RAM_AUTO_1R1W.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_flow_control_loop_pipe_sequential_init.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_WRITE_LOOP.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_VITIS_LOOP_14_1.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_SHIFT.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_READ_LOOP4.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_READ_LOOP3.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_dut_Pipeline_READ_LOOP.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_w_digits_data_V_RAM_AUTO_1R1W.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_SHIFT6.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_SHIFT5.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_SHIFT.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_REM.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_PARTIAL.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_NORMALIZE.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_COMPARE.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_CLEAR_UPPER.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide_Pipeline_ADJUST.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut_divide.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fpga-design/dut.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fifo_8x2048.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/src/fifo_32x512.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/system.v
      D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/synth/vivado_system.v
    }
      rt::read_verilog -include {
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/3007/hdl
    d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ec67/hdl
  } {
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_lite_0_0/synth/vivado_system_xillybus_lite_0_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_ip_0_0/work/xillybus.srcs/sources_1/imports/verilog/xillybus_ip.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_ip_0_0/synth/vivado_system_xillybus_ip_0_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillyvga_0_0/work/xillyvga.srcs/sources_1/imports/verilog/xillyvga_core.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillyvga_0_0/work/xillyvga.srcs/sources_1/imports/verilog/xillyvga.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillyvga_0_0/synth/vivado_system_xillyvga_0_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/synth/vivado_system_processing_system7_0_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/synth/vivado_system_xbar_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_3/synth/vivado_system_auto_pc_3.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/synth/vivado_system_auto_pc_0.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1/synth/vivado_system_auto_pc_1.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2/synth/vivado_system_auto_pc_2.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v
      d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xlconcat_0_0/synth/vivado_system_xlconcat_0_0.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_5 d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/25a8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_6 d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8ae1/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib d:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/synth/vivado_system_rst_processing_system7_0_100M_0.vhd
      rt::read_vhdl -lib xpm D:/Study/Tai_lieu/Nhung_bao_mat/xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/realtime/xillydemo_synth.xdc
    rt::sdcChecksum
    set rt::top xillydemo
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/Study/Tai_lieu/Nhung_bao_mat/Final/Code/Test2/zedboard_project/xillybus/vivado/xillydemo.runs/synth_1/.Xil/Vivado-20536-GunDx/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
