set_property SRC_FILE_INFO {cfile:C:/Users/quang/Desktop/Pynq/TRNG-Pynq/TRNG-Pynq.srcs/constrs_1/new/ZynqCons.xdc rfile:../../../TRNG-Pynq.srcs/constrs_1/new/ZynqCons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U8  IOSTANDARD LVCMOS33 } [get_ports { uart_rtl_rxd }]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W6  IOSTANDARD LVCMOS33 } [get_ports { uart_rtl_txd }]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U10 IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[5] }]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y11 IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[0] }]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y12 IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[1] }]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W11 IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[2] }]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V11 IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[3] }]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T5  IOSTANDARD LVCMOS33 } [get_ports { arduino_a0_a5_tri_io[4] }]
